# Generated by Django 4.2.3 on 2023-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('I', 'Italian'), ('G', 'Greek'), ('F', 'French')], default='G', max_length=1)),
                ('course', models.CharField(choices=[('SA', 'Salads'), ('MC', 'Main Course'), ('DS', 'Dessert'), ('SO', 'Soup'), ('FI', 'Fish'), ('CH', 'Cheese plate'), ('AP', 'Antipasti'), ('MZ', 'Mezes')], default='MC', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'MenuItems',
            },
        ),
    ]
