# Generated by Django 4.2.3 on 2023-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('I', 'Italian'), ('G', 'greek'), ('F', 'French')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='description',
            field=models.CharField(default='Greek', max_length=250),
            preserve_default=False,
        ),
    ]
