# Generated by Django 4.2.3 on 2023-07-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0002_menuitems_category_menuitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='course',
            field=models.CharField(choices=[('SA', 'Salads'), ('MC', 'Main Course'), ('DS', 'Dessert'), ('SO', 'Soup'), ('FI', 'Fish'), ('CH', 'Cheese plate'), ('AP', 'Antipasti'), ('MZ', 'Mezes')], default='MC', max_length=2),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('I', 'Italian'), ('G', 'Greek'), ('F', 'French')], default='G', max_length=1),
        ),
    ]
